name: Testing
on:
  pull_request:
    branches:
    - develop
jobs:
  test:
    name: Testing Swift Package and iOS app
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup SSH Keys and known_hosts
          env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          run: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY_FH_NETWORKING }}"
      - name: Force XCode 11.3
        run: sudo xcode-select -switch /Applications/Xcode_11.3.app
      - name: Testing iOS app
        run: exec ./.github/scripts/test_app.sh
