name: Deploying
on:
  pull_request:
    branches:
    - develop
jobs:
  deploy:
    name: Deploying to Testflight
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install gpg
        run: brew install gnupg
      - name: Setup provisioning profile
        env:
          IOS_KEYS_PROVISIONING: ${{ secrets.IOS_KEYS_PROVISIONING }}
          IOS_KEYS_CERTIFICATE: ${{ secrets.IOS_KEYS_CERTIFICATE }}
        run: ./.github/secrets/decrypt_secrets.sh
      - name: Set up ssh-agent
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: github.com
      - name: Setup known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
      - name: Cleaning project
        run: ./.github/scripts/01_clean_project.sh
      - name: Increase Version
        run: ./.github/scripts/02_clean_project.sh
      - name: Archiving project
        env:
          PR_NUMBER: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        run: ./.github/scripts/03_archive_project.sh
      - name: Exporting .ipa
        run: ./.github/scripts/04_export_ipa.sh
      - name: Publishing app
        if: success()
        env:
          APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
          APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
        run: ./.github/scripts/05_publish_testflight.sh
